export const fieldMapping = [
  {
    name: "payerEntityName",
    label: "Payer Entity Name",
    type: "text",
    required: true,
  },
  {
    name: "payerEntityAbn",
    label: "Payer Entity ABN",
    type: "text",
    required: false,
  },
  {
    name: "payerEntityAcnArbn",
    label: "Payer Entity ACN/ARBN",
    type: "text",
    required: false,
  },
  {
    name: "payeeEntityName",
    label: "Payee Entity Name",
    type: "text",
    required: true,
  },
  {
    name: "payeeEntityAbn",
    label: "Payee Entity ABN",
    type: "text",
    required: false,
  },
  {
    name: "payeeEntityAcnArbn",
    label: "Payee Entity ACN/ARBN",
    type: "text",
    required: false,
  },
  {
    name: "paymentAmount",
    label: "Payment Amount",
    type: "text",
    required: true,
  },
  {
    name: "description",
    label: "Description",
    type: "text",
    required: false,
  },
  { name: "supplyDate", label: "Supply Date", type: "date", required: false },
  {
    name: "paymentDate",
    label: "Payment Date",
    type: "date",
    required: true,
  },
  {
    name: "contractPoReferenceNumber",
    label: "Contract/PO Reference Number",
    type: "text",
    required: false,
  },
  {
    name: "contractPoPaymentTerms",
    label: "Contract/PO Payment Terms",
    type: "text",
    required: false,
  },
  {
    name: "noticeForPaymentIssueDate",
    label: "Notice for Payment Issue Date",
    type: "date",
    required: false,
  },
  {
    name: "noticeForPaymentTerms",
    label: "Notice for Payment Terms",
    type: "text",
    required: false,
  },
  {
    name: "invoiceReferenceNumber",
    label: "Invoice Reference Number",
    type: "text",
    required: false,
  },
  {
    name: "invoiceIssueDate",
    label: "Invoice Issue Date",
    type: "date",
    required: false,
  },
  {
    name: "invoiceReceiptDate",
    label: "Invoice Receipt Date",
    type: "date",
    required: false,
  },
  {
    name: "invoiceAmount",
    label: "Invoice Amount",
    type: "text",
    required: false,
  },
  {
    name: "invoicePaymentTerms",
    label: "Invoice Payment Terms",
    type: "text",
    required: false,
  },
  {
    name: "invoiceDueDate",
    label: "Invoice Due Date",
    type: "date",
    required: false,
  },
  {
    name: "isTcp",
    label: "TCP",
    type: "checkbox",
    required: false,
  },
  {
    name: "tcpExclusionComment",
    label: "TCP Exclusion Comment",
    type: "text",
    required: false,
  },
  {
    name: "peppolEnabled",
    label: "Peppol eInvoice Enabled",
    type: "checkbox",
    required: false,
  },
  {
    name: "rcti",
    label: "RCTI",
    type: "checkbox",
    required: false,
  },
  {
    name: "creditCardPayment",
    label: "Credit Card Payment",
    type: "checkbox",
    required: false,
  },
  {
    name: "creditCardNumber",
    label: "Credit Card Number",
    type: "text",
    required: false,
  },
  {
    name: "partialPayment",
    label: "Partial Payment",
    type: "checkbox",
    required: false,
  },
  {
    name: "paymentTerm",
    label: "Payment Term",
    type: "text",
    required: false,
  },
  {
    name: "excludedTcp",
    label: "Excluded TCP",
    type: "checkbox",
    required: false,
  },
  {
    name: "explanatoryComments1",
    label: "Explanatory Comments",
    type: "textArea",
    required: false,
  },
  {
    name: "isSb",
    label: "Small Business",
    type: "checkbox",
    required: false,
  },
  {
    name: "paymentTime",
    label: "Payment Time (days)",
    type: "text",
    required: false,
  },
  {
    name: "explanatoryComments2",
    label: "Explanatory Comments",
    type: "textArea",
    required: false,
  },
  {
    name: "notes",
    label: "Notes",
    type: "textArea",
    required: false,
  },
];
