export const fieldMapping = [
  {
    name: "payerEntityName",
    label: "Payer Entity Name",
    type: "text",
    required: true,
  },
  {
    name: "payerEntityAbn",
    label: "Payer Entity ABN",
    type: "text",
    required: false,
  },
  {
    name: "payerEntityAcnArbn",
    label: "Payer Entity ACN/ARBN",
    type: "text",
    required: false,
  },
  {
    name: "payeeEntityName",
    label: "Payee Entity Name",
    type: "text",
    required: true,
  },
  {
    name: "payeeEntityAbn",
    label: "Payee Entity ABN",
    type: "text",
    required: false,
  },
  {
    name: "payeeEntityAcnArbn",
    label: "Payee Entity ACN/ARBN",
    type: "text",
    required: false,
  },
  {
    name: "paymentAmount",
    label: "Payment Amount",
    type: "text",
    required: true,
  },
  {
    name: "description",
    label: "Description",
    type: "text",
    required: false,
  },
  { name: "supplyDate", label: "Supply Date", type: "date", required: false },
  {
    name: "paymentDate",
    label: "Payment Date",
    type: "date",
    required: true,
  },
  {
    name: "contractPoReferenceNumber",
    label: "Contract/PO Reference Number",
    type: "text",
    required: false,
  },
  {
    name: "contractPoPaymentTerms",
    label: "Contract/PO Payment Terms",
    type: "text",
    required: false,
  },
  {
    name: "noticeForPaymentIssueDate",
    label: "Notice for Payment Issue Date",
    type: "date",
    required: false,
  },
  {
    name: "noticeForPaymentTerms",
    label: "Notice for Payment Terms",
    type: "text",
    required: false,
  },
  {
    name: "invoiceReferenceNumber",
    label: "Invoice Reference Number",
    type: "text",
    required: false,
  },
  {
    name: "invoiceIssueDate",
    label: "Invoice Issue Date",
    type: "date",
    required: false,
  },
  {
    name: "invoiceReceiptDate",
    label: "Invoice Receipt Date",
    type: "date",
    required: false,
  },
  {
    name: "invoicePaymentTerms",
    label: "Invoice Payment Terms",
    type: "text",
    required: false,
  },
  {
    name: "invoiceDueDate",
    label: "Invoice Due Date",
    type: "date",
    required: false,
  },
];
