name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        env:
          CI: false
        run: npm run build

      - name: Prepare deployment bundle
        run: |
          mkdir -p eb-bundle
          cp -r build/* eb-bundle/
          cp -r .ebextensions eb-bundle/
          cp package.json eb-bundle/
          zip -r eb-bundle/deployment.zip eb-bundle/*

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-2
          application_name: sit.monochrome-frontend
          environment_name: Sitmonochrome-frontend-env
          version_label: ${{ github.sha }}
          deployment_package: eb-bundle/deployment.zip
